### ISSUE TITLE
Supprimer duplication sur vérification du JWT

### ISSUE THREAD

**Issue by egaillot** [betagouv/oots-france#60]
… entre https://github.com/betagouv/oots-france/blob/7fa954e8fa19a2e2d9ed241c8f7ef79d3ce49017/src/adaptateurs/adaptateurChiffrement.js#L18-L19 et https://github.com/betagouv/oots-france/blob/7fa954e8fa19a2e2d9ed241c8f7ef79d3ce49017/src/adaptateurs/adaptateurFranceConnectPlus.js#L37-L38

**Comment by egaillot** [comment]
Une possible feuille de route :
- Modifier API `adaptateurChiffrement/verifieJeton` pour prendre en paramètre le secret
- Utiliser cette fonction depuis l'`adaptateurFranceConnectPlus`
- Ajouter un `catch` sur `verifieJeton` et caractériser avec une `ErreurVerificationJeton`

**Comment by Fabinout** [comment]
Corrigé avec la Pull Request #67
